spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  config:
    import:
      - file:src/main/resources/key/dbKey.yml
      - file:src/main/resources/key/ossKey.yml
      - file:src/main/resources/key/xxlKey.yml
#      - file:/www/code/ossKey.yml

xxl:
  job:
    admin:
      addresses: ${xxl.job.admin.addresses}
    executor:
      appname: ${xxl.job.executor.appname}
      ip:
      port: ${xxl.job.executor.port}
      logpath: ${xxl.job.executor.logpath}
      logretentiondays: 30
    accessToken:

mybatis:
  mapper-locations: classpath*:src/main/resources/mapper/*.xml
  type-aliases-package: app.xmum.xplorer.backend.groupbooking.pojo

logging:
  config: classpath:log4j2.xml
  level:
    root: info